config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'films#index'

  resources :actors, only: %i[index show new create destroy]
  resources :films, only: %i[index show create destroy] do
    scope module: :films do
      resources :reviews, only: %i[create]
    end
  end

  resources :reviews, only: :destroy
end

app/models/actor.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: actors
#
#  id               :bigint           not null, primary key
#  description      :text
#  full_name        :string
#  gender           :string
#  is_married       :boolean          default(FALSE)
#  number_of_oscars :integer          default(0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Actor < ApplicationRecord
  validates :full_name, presence: true

  # TODO: add more validations

  enum gender: {
    male:   MALE   = 'male',
    female: FEMALE = 'female',
    other:  OTHER  = 'other'
  }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: films
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Film < ApplicationRecord
  MIN_DESCRIPTION_LENGTH = 50
  MAX_DESCRIPTION_LENGTH = 250

  has_many :reviews, dependent: :delete_all
  has_one_attached :photo

  validates :name, :description, presence: true
  validates :description,
            length: { minimum: MIN_DESCRIPTION_LENGTH, maximum: MAX_DESCRIPTION_LENGTH }
end

app/models/review.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: reviews
#
#  id         :bigint           not null, primary key
#  text       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  film_id    :bigint
#
# Indexes
#
#  index_reviews_on_film_id  (film_id)
#
# Foreign Keys
#
#  fk_rails_...  (film_id => films.id) ON DELETE => cascade
#
class Review < ApplicationRecord
  MIN_TEXT_LENGTH = 10
  MAX_TEXT_LENGTH = 100

  belongs_to :film

  validates :text, presence: true
  validates :text, length: { minimum: MIN_TEXT_LENGTH, maximum: MAX_TEXT_LENGTH }
end

app/controllers/actors_controller.rb
# frozen_string_literal: true

class ActorsController < ApplicationController
  before_action :find_actor!, only: %i[show destroy]

  def index
    @pagy, @actors = pagy(Actor.order(created_at: :desc))
  end

  def new
    @actor = Actor.new
  end

  def create
    @actor = Actor.create(actor_params)

    return render :new if @actor.errors.any?

    redirect_to actors_path, notice: I18n.t('actors.create.success')
  end

  def destroy
    @actor.destroy!

    redirect_to actors_path, notice: I18n.t('actors.destroy.message', name: @actor.full_name)
  end

  private

  def find_actor!
    @actor = Actor.find(params[:id])
  end

  def actor_params
    params.require(:actor).permit(:full_name, :description, :number_of_oscars, :gender, :is_married)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/films/reviews_controller.rb
# frozen_string_literal: true

module Films
  class ReviewsController < ApplicationController
    def create
      @film   = Film.find(params[:film_id])
      @review = Review.create(film: @film, **comment_params)

      return create_failure if @review.errors.any?

      redirect_to film_path(@film, anchor: 'new-review'),
                  notice: I18n.t('films.reviews.create.success')
    end

    private

    def comment_params
      params.require(:review).permit(:text)
    end

    def create_failure
      redirect_to film_path(@film, anchor: 'new-review'),
                  alert: @review.errors.full_messages.first
    end
  end
end

app/controllers/films_controller.rb
# frozen_string_literal: true

class FilmsController < ApplicationController
  before_action :find_film!, only: %i[show destroy]

  def index
    @films = Film.includes(:photo_blob).order(created_at: :desc)
  end

  def show
    @review = Review.new
  end

  def new
    @film = Film.new
  end

  def create
    @film = Film.create(film_params)

    return render :new if @film.errors.any?

    redirect_to films_path, notice: I18n.t('films.create.success')
  end

  # JSON response example
  def destroy
    @film.destroy!

    respond_to do |format|
      format.html { redirect_to films_path, notice: I18n.t('films.destroy.message') }
      format.json do
        render json: { data: { message: I18n.t('films.destroy.json_message', name: @film.name) } }
      end
    end
  end

  private

  def find_film!
    @film = Film.find(params[:id])
  end

  def film_params
    params.require(:film).permit(:name, :description)
  end
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  def destroy
    review = Review.find(params[:id])
    review.destroy

    redirect_to film_path(review.film, anchor: 'new-review'),
                notice: I18n.t('reviews.destroy.message')
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend

  def app_name
    t('app_name')
  end

  def page_title
    return controller_title unless I18n.exists?(action_page_title_key)

    t('page_title', app_name: app_name, title: t(action_page_title_key))
  end

  protected

  def current_action
    return :new  if action_name == 'create'
    return :edit if action_name == 'update'

    params[:action]
  end

  private

  def action_page_title_key
    "#{controller_locale_path}.#{current_action}.title"
  end

  def controller_locale_path
    params[:controller].tr('/', '.')
  end

  def controller_title
    t(
      'page_title',
      app_name: app_name,
      title:    t("#{controller_locale_path}.title", default: t('default_page_title'))
    )
  end
end

app/helpers/i18n_helper.rb
# frozen_string_literal: true

module I18nHelper
  def humanize_enum(model, enum_field, value)
    return if value.blank?

    I18n.t(
      "enums.#{model.name.underscore}.#{enum_field.to_s.pluralize}.#{value}",
      default: value.to_s.humanize
    )
  end

  def enum_collection_for_select(model, enum_field, **params)
    model
      .send(enum_field.to_s.pluralize)
      .keys
      .map { |value| [humanize_enum(model, enum_field, value), value] }
      .prepend(build_enum_placeholder(model, enum_field, **params))
      .compact
  end

  private

  def build_enum_placeholder(model, enum_field_name, **params)
    return unless params[:placeholder]

    Array[humanize_enum(model, enum_field_name, :placeholder), nil, disabled: params[:disabled]]
  end
end

app/helpers/layouts_helper.rb
# frozen_string_literal: true

module LayoutsHelper
  def controller_javascript_pack_tag(**options)
    javascript_pack_tag(params[:controller].to_s, **options)
  rescue Webpacker::Manifest::MissingEntryError
    Rails.logger.debug { "No javascript pack for `#{params[:controller]}.js`" }

    nil
  end

  def controller_stylesheet_pack_tag(**options)
    stylesheet_pack_tag(params[:controller].to_s, **options)
  rescue Webpacker::Manifest::MissingEntryError
    Rails.logger.debug { "No stylesheet pack for `#{params[:controller]}.css`" }

    nil
  end

  def action_javascript_pack_tag(**options)
    javascript_pack_tag("#{params[:controller]}/#{current_action}", **options)
  rescue Webpacker::Manifest::MissingEntryError
    Rails.logger.debug { "No javascript pack for `#{params[:controller]}/#{current_action}.js`" }

    nil
  end

  def action_stylesheet_pack_tag(**options)
    stylesheet_pack_tag("#{params[:controller]}/#{current_action}", **options)
  rescue Webpacker::Manifest::MissingEntryError
    Rails.logger.debug { "No stylesheet pack for `#{params[:controller]}/#{current_action}.css`" }

    nil
  end

  def sidebar_link(label_or_path, path_or_controller, controller = nil, &block)
    klass = (controller || path_or_controller).to_s == params[:controller] ? 'is-active' : ''

    return link_to(label_or_path, path_or_controller, class: klass) if block.blank?

    link_to(label_or_path, class: klass, &block)
  end
end

app/views/actors/_list_item.html.erb
<article class="media container">
  <figure class="media-left actor-photo">
    <p class="image is-128x128">
      <%= image_tag 'https://bulma.io/images/placeholders/128x128.png' %>
    </p>
  </figure>

  <div class="media-content">
    Add author card
  </div>
  <div class="media-right">
    <%= link_to '', actor_path(item), method: :delete,
                                      class: 'delete',
                                      data: { confirm: t('.delete_confirm') } %>
  </div>
</article>

app/views/actors/index.html.erb
<%= content_for :content_title do %>
  Normalized actors title should be here
<% end %>

<% content_for :content_title_actions do %>
  <%= link_to new_actor_path do %>
    <span class="icon-text">
      <span class="icon">
        <i class="fas fa-plus-circle"></i>
      </span>
      <span><%= t('generic.add_new') %></span>
    </span>
  <% end %>
<% end %>

<div class="actors" data-js-actors>
  <% if @actors.any? %>

    <% @actors.each do |film| %>
      <%= render 'list_item', item: film %>
    <% end %>

    <%== pagy_bulma_nav(@pagy) %>

  <% else %>
    <p class="has-text-centered is-size-6"><%= t('.no_items') %></p>
  <% end %>
</div>

app/views/actors/new.html.erb
<% content_for :content_title_class %>
<% content_for :content_title_actions do %>
  <%= link_to actors_path do %>
    <span class="icon-text">
      <span class="icon">
        <i class="fas fa-arrow-left"></i>
      </span>
      <span><%= t('generic.back') %></span>
    </span>
  <% end %>
<% end %>

<%= content_for :content_title do %>
  <span class="icon-text">
    <span class="icon">
      <i class="fas fa-plus"></i>
    </span>
    <span><%= t('.title') %></span>
  </span>
<% end %>

<%= simple_form_for @actor do |f| %>
  <div class="content p-5 px-6">
    <div class="columns">
      <div class="column is-two-fifths">
        <%= f.input :full_name, required: false %>
        <%= f.input :description, as: :text %>
      </div>

      <div class="column">
        <%= f.input :number_of_oscars, as: :integer, input_html: { value: nil } %>
        <%= f.input :gender, collection: enum_collection_for_select(Actor, :gender, placeholder: true),
                             prompt: false %>
        <%= f.input :is_married, as: :boolean %>
      </div>
    </div>
  </div>

  <div class="content-footer has-text-right">
    <%= f.button :submit, value: t('generic.save') %>
  </div>
<% end %>

app/views/actors/show.html.erb
<% content_for :content_title_class, 'is-danger' %>
<%= content_for :content_title do %>
  <span class="icon-text">
    <span class="icon">
      <i class="fas fa-user"></i>
    </span>
    <span><%= @actor.full_name %></span>
  </span>
<% end %>

<% content_for :content_title_actions do %>
  <%= link_to actors_path do %>
    <span class="icon-text">
      <span class="icon">
        <i class="fas fa-arrow-left"></i>
      </span>
      <span><%= t('generic.back') %></span>
    </span>
  <% end %>
<% end %>

<div class="content p-5 px-6">
  <div class="columns">
    <div class="column is-two-fifths">
      <figure class="image film-photo m-0">
        <%= image_tag 'https://bulma.io/images/placeholders/128x128.png' %>
      </figure>
    </div>
    <div class="column">
      <div class="columns">
        <div class="group column is-half mb-5">
          <label class="has-text-weight-bold mr-3">
            <%= Actor.human_attribute_name(:gender) %>
            :
          </label>
          <p class="has-text-justified is-inline"><%= @actor.gender %></p>
        </div>

        <div class="group column is-half mb-5">
          <label class="has-text-weight-bold mr-3">
            <%= Actor.human_attribute_name(:number_of_oscars) %>
            :
          </label>
          <p class="has-text-justified is-inline"><%= @actor.number_of_oscars %></p>
        </div>
      </div>

      <div class="group has-text-justified">
        <%= @actor.description %>
      </div>
    </div>
  </div>
</div>

app/views/films/_list_item.html.erb
<article class="media container">
  <figure class="media-left film-photo">
    <p class="image is-128x128">
      <%= image_tag item.photo.blank? ? 'https://bulma.io/images/placeholders/128x128.png' : url_for(item.photo) %>
    </p>
  </figure>
  <div class="media-content">
    <div class="content">
      <p>
        <%= item.name %>
        <br>
        <%= item.description %>
      </p>
    </div>

    <div>
      0
      <i class="fa fa-eye"></i>
    </div>

  </div>
  <div class="media-right">
    <%= button_tag '', class: 'delete', data: { 'js-film-delete': true,
                                                turbolinks: false,
                                                confirm: t('.delete_confirm'),
                                                url: film_path(item) } %>
  </div>
</article>

app/views/films/index.html.erb
<%= content_for :content_title do %>
  <span class="icon-text">
    <span class="icon">
      <i class="fas fa-film"></i>
    </span>
    <span><%= t('films.nav') %></span>
  </span>
<% end %>

<div class="films" data-js-films>
  <% if @films.any? %>

    <% @films.each do |film| %>
      <%= render 'list_item', item: film %>
    <% end %>

  <% else %>
    <p class="has-text-centered is-size-6"><%= t('.no_items') %></p>
  <% end %>
</div>

app/views/films/reviews/_form.html.erb
<%= form_for [film, review], html: { id: 'new-review' } do |f| %>
  <article class="media mb-5">
    <div class="media-content">
      <div class="field">
        <p class="control">
          <%= f.text_area :text, class: 'textarea', placeholder: t('.text_placeholder') %>
        </p>
      </div>
      <%= f.submit t('generic.submit'), class: 'button is-info is-pulled-right' %>
    </div>
  </article>
<% end %>

app/views/films/reviews/_list.html.erb
<% if reviews.any? %>

  <% reviews.each do |review| %>
    <%= render 'films/reviews/list_item', model: review %>
  <% end %>

<% else %>
  <p class="has-text-centered is-size-6"><%= t('.no_items') %></p>
<% end %>

app/views/films/reviews/_list_item.html.erb
<article class="media">
  <div class="media-content">
    <div class="content">
      <p>
        <strong><%= t('generic.anonymous_user') %></strong>
        <br>
        <%= model.text %>
      </p>
    </div>
  </div>

  <div class="media-right">
    <%= link_to '', review_path(model), method: :delete,
                                        class: 'delete',
                                        data: { confirm: t('.delete_confirm') } %>
  </div>
</article>

app/views/films/show.html.erb
<% content_for :content_title_class, 'is-link' %>
<%= content_for :content_title do %>
  <span class="icon-text">
    <span class="icon">
      <i class="fas fa-camera-retro"></i>
    </span>
    <span><%= @film.name %></span>
  </span>
<% end %>

<% content_for :content_title_actions do %>
  <%= link_to films_path do %>
    <span class="icon-text">
      <span class="icon">
        <i class="fas fa-arrow-left"></i>
      </span>
      <span><%= t('generic.back') %></span>
    </span>
  <% end %>
<% end %>

<div class="content p-5 px-6">
  <div class="columns">
    <div class="column is-two-fifths">
      <figure class="image film-photo m-0">
        <%= image_tag @film.photo.blank? ? 'https://bulma.io/images/placeholders/128x128.png' : url_for(@film.photo) %>
      </figure>
    </div>
    <div class="column has-text-justified">
      <%= @film.description %>
    </div>
  </div>

  <%= render 'films/reviews/form', film: @film, review: @review %>
  <%= render 'films/reviews/list', reviews: @film.reviews %>
</div>

app/views/layouts/_content.html.erb
<div class="section column is-four-fifth pt-0">
  <% if yield(:content_title).present? %>
    <div class="<%= ['hero', 'is-small', 'is-primary', yield(:content_title_class)].compact.join(' ') %>">
      <div class="hero-body level">
        <p class="title level-left mb-0">
          <%= yield(:content_title) %>
        </p>
        <div class="actions level-right">
          <%= yield(:content_title_actions) %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="<%= ['box', 'content', yield(:content_container_class)].reject(&:blank?).join(' ') %>">
    <%= yield %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <%= link_to t('company_name'), 'https://www.leobit.com', class: 'has-text-white has-text-weight-bold' %>
      ©
      <%= t('initial_year') %>
    </p>
  </div>
</footer>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar" class="sidebar column is-one-fifth p-0">
  <div class="menu">
    <p class="menu-label">General</p>
    <ul class="menu-list">
      <li><%= sidebar_link t('actors.nav'), actors_path, :actors %></li>
      <li>
        <%= sidebar_link films_path, :films do %>
        <span class="icon-text">
        <span class="icon">
          <i class="fas fa-film"></i>
        </span>
        <span><%= t('films.nav') %></span>
      </span>
        <% end %>
      </li>
    </ul>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= yield(:title).presence || page_title %></title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_pack_tag 'favicon.png' %>

    <%= stylesheet_packs_with_chunks_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- That's not a Rails magic, but manually written functionality in LayoutsHelper -->
    <%= controller_stylesheet_pack_tag media: 'all', data: { turbolinks_track: :reload } %>
    <%= action_stylesheet_pack_tag     media: 'all', data: { turbolinks_track: :reload } %>

    <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- That's not a Rails magic, but manually written functionality in LayoutsHelper -->
    <%= controller_javascript_pack_tag data: { turbolinks_track: :reload } %>
    <%= action_javascript_pack_tag     data: { turbolinks_track: :reload } %>
  </head>

  <body>
    <div id="flash-container" data-flash="<%= flash.to_h.to_json %>"></div>

    <div id="body-wrapper" class="section columns">
      <%= render 'layouts/sidebar' %>
      <%= render 'layouts/content' %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>